### ISSUE TITLE
Bug Report: Some notes stacked on top of each other in Lit Up hard mode chart preventing FC's, plus an offbeat note

### ISSUE THREAD

**Issue by JackXson-Real** [FunkinCrew/Funkin#2350]
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Yes, just play Lit Up hard mode at the provided time stamps below.

## Please describe your issue. Provide extensive detail and images if possible.

There are 2 notes in the Lit Up hard mode chart that are stacked directly on top of the same note making FCing the song impossible. Here are some images that show exactly which notes are overlapped. It can easily be fixed by deleting both of the notes and replacing one.
![screenshot-2024-05-08-13-09-44](https://github.com/FunkinCrew/Funkin/assets/32755192/6a83ae5b-35d5-4c0f-beb6-6c97304dd4dd)
![screenshot-2024-05-08-13-10-49](https://github.com/FunkinCrew/Funkin/assets/32755192/d2d44792-be0b-4584-90c6-3346b9818a7b)

Aside from these 2 notes, there is one down note that is about half a second earlier than when it should be. The image below shows which note is placed early (it is selected and shows the green box around it) and where it should be placed (where the cursor is hovering over)
![screenshot-2024-05-08-13-11-58](https://github.com/FunkinCrew/Funkin/assets/32755192/39744ddf-891d-496c-8dbe-b34e06af2e50)

**Comment by JamJarIsDumb** [comment]
Hope this gets fixed asap

**Comment by Geeky347** [comment]
They fixed the note stacking, but it seems that the mistiming is still there.

**Comment by JackXson-Real** [comment]
Yep, @EliteMasterEric please do this quick fix for the mistimed Lit Up note

**Comment by EliteMasterEric** [comment]
Oh yeah this was fixed in v0.4.1.

**Comment by JamJarIsDumb** [comment]
![image](https://github.com/FunkinCrew/Funkin/assets/92594242/b12aa461-d915-460c-b060-7e835c2d884d)
It was fixed on the normal and easy charts, however hard still has the mistimed note. (Playing on 0.4.1)

**Comment by JackXson-Real** [comment]
> ![image](https://private-user-images.githubusercontent.com/92594242/340101005-b12aa461-d915-460c-b060-7e835c2d884d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NjM0NjUsIm5iZiI6MTcxODU2MzE2NSwicGF0aCI6Ii85MjU5NDI0Mi8zNDAxMDEwMDUtYjEyYWE0NjEtZDkxNS00NjBjLWIwNjAtN2U4MzVjMmQ4ODRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE4MzkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMDkwMzMwNGYzOTRlMjM4NGM2NzEzMDc4MWJhZmE1OTI1MjA2ZTdhMWVmM2Q4ZDFlNzkwNjk4NDViYjNmOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9QMHAe7gnYok3geL6ofCUz7zJrR4md6SE1O26sGOiWk) It was fixed on the normal and easy charts, however hard still has the mistimed note. (Playing on 0.4.1)

You must be on the wrong version since it’s fixed for me

**Comment by JamJarIsDumb** [comment]
Video of me playing on 0.4.1 with the chart error, but on a fresh install just now it seems to be gone. I have not touched the chart at all for the version in the video so I still dont know why its there, but it seems to be fixed now. Honestly really confusing but I can confirm it is no longer present in the latest itch build
[https://drive.google.com/file/d/1MAXI29ae4xfUH7S22ypTqPQGFdUu9tMa/view?usp=sharing](url)
