### ISSUE TITLE
Bug Report: [Game keeps playing instrumental when on chart editor and window not focused]

### ISSUE THREAD

**Issue by amyspark-ng** [FunkinCrew/Funkin#2430]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
1. Open chart editor
2. Open any song
3. Press play
4. Minimize window

## Please describe your issue. Provide extensive detail and images if possible.
The instrumental will keep playing when the window is minimized, but not vocals, and when you go back to the game the playbar will have passed through a bunch of notes, causing them all to play at the same time (?) making them sound very loud, i don't think this is intended behaviour, close if it's

**Comment by amyspark-ng** [comment]
it's fun until your ears pop when you hear the sound of all the notes at once after focusing the window again

**Comment by Hundrec** [comment]
Also just noticed that the vocals are a little delayed when this happens

https://github.com/user-attachments/assets/841d48b2-5105-435d-8afa-4d73417fb21a

**Comment by Hundrec** [comment]
Looks like they fixed this in 0.5.2!
Has anyone encountered this?

**Comment by amyspark-ng** [comment]
me? i don't think it has been fixed

**Comment by Hundrec** [comment]
Really? My copy of 0.5.2 seems to actually pause the chart editor whenever it loses focus

**Comment by AbnormalPoof** [comment]
Reproduced. Likely a Haxe issue since pausing the game during debugging produces the same result.

![image](https://github.com/user-attachments/assets/b12f6b44-ac31-4bb0-bf74-977f92d5a47f)

**Comment by Hundrec** [comment]
Looks like fixing #2375 also made the vocals not desync when refocusing!
This issue remains a thing, but at least you can enjoy rapidly tabbing in and out to mute the vocals :)
