### ISSUE TITLE
Bug Report: Ghost tapping-like behavior after holding a note and pausing

### ISSUE THREAD

**Issue by MightyTheArmiddilo** [FunkinCrew/Funkin#6472]
### Version

0.7.5 develop

### Description (include any images, videos, errors, or crash logs)

I was testing the latest develop 0.7.5 build, and noticed a problem. When a note key is being held, you can pause the game, unhold the key, and unpause, the note will be stuck in the pressed animation.

This is is similar to #2227, sure, but the difference is that in the release builds, pressing the key again in any context will fix it. HERE, however, you can keep touching that key, and it'll stay pressed. AND, when it is in effect, you can GHOST TAP.

(YouTube video since GitHub hates my file)
https://youtu.be/9aAPxVXk40w?si=TrJF0lRcUAQ9I0kD

### Steps to Reproduce

1. Play any song
2. Hit any sing key and then pause the game
3. You can now ghost tap!

**Comment by Fru001** [comment]
official ghost tapping :0

**Comment by charlesisfeline** [comment]
this should be fixed asap cuz we **do not** allow ghost tapping outside of mobile

**Comment by FuroYT** [comment]
> this should be fixed asap cuz we **do not** allow ghost tapping outside of mobile

More like when the game is not compiled with `FEATURE_GHOST_TAPPING`

**Comment by MightyTheArmiddilo** [comment]
Pretty sure this can be fixed by #4145 since it's linked to the same problem with checking `isGamePaused` when releasing/pressing a key. Just this time it's causing the ghost tapping because of commit f7cb738803fb0eda6e946370c3455e4596f0b1f8 checking if it's still being "held" by using the `Strumline` class's `isKeyHeld` function.

**Comment by charlesisfeline** [comment]
> More like when the game is not compiled with `FEATURE_GHOST_TAPPING`

yeah that

**Comment by NotHyper-474** [comment]
> Pretty sure this can be fixed by [#4145](https://github.com/FunkinCrew/Funkin/pull/4145) since it's linked to the same problem with checking `isGamePaused` when releasing/pressing a key. Just this time it's causing the ghost tapping because of commit [f7cb738](https://github.com/FunkinCrew/Funkin/commit/f7cb738803fb0eda6e946370c3455e4596f0b1f8) checking if it's still being "held" by using the `Strumline` class's `isKeyHeld` function.

I just tested that PR and unfortunately it does not fix the issue.

https://github.com/user-attachments/assets/04c0cbb0-05d4-4837-8971-6e1e158fd7e7

**Comment by Hundrec** [comment]
oh my god bruh

**Comment by DustedDustin** [comment]
Sorry guys no more week 8 thanks to this blunder

**Comment by DustedDustin** [comment]
We're never getting this game

**Comment by MightyTheArmiddilo** [comment]
For now, it'd probably be easier to get rid of the lines checking if the game is paused.

**Comment by NotHyper-474** [comment]
> For now, it'd probably be easier to get rid of the lines checking if the game is paused.

Your wish has been granted #6496

**Comment by DatGamerYoloYT** [comment]
> this should be fixed asap cuz we **do not** allow ghost tapping outside of mobile

why isn't ghost tapping allowed outside of mobile?

**Comment by charlesisfeline** [comment]
> why isn't ghost tapping allowed outside of mobile?

https://www.youtube.com/watch?v=V0W2QcSj6UQ
